### ISSUE TITLE
AptStatus

### ISSUE THREAD

**Issue by kevinrossen** [WilliamCipriano/OpenDental-Patient-Reminder#1]
It looks like the reminders are only being set to send to patients with a 1 status, which works for appointments that have a "Scheduled" status. There's another status that some practices use called ASAP, which functions as a short call list. It's status value is 4, so you might consider changing entries like "AptStatus=1" to "AptStatus IN (1,4)" so all patients who are expected to show up receive the reminders.

**Comment by WilliamCipriano** [comment]
Hey Kevin,

Thanks for your interest in my project and I hope you got some use out of it. I left the dental IT business about 6 months ago and without access to any open dental databases I wouldn't feel right pushing out code that I haven't had a chance to test and vet in production. I have updated the project page to reflect that this project is no longer maintained (in case opendental changes their database schema and it not longer works). To be honest this project was devolved rather early in on in my learning of Python and I'd likely entirely rewrite the thing now but if you'd like to fork it for your own purposes feel free.

Thanks again,
Will Cipriano
